spring:
  application:
    name: notes
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: ${EXPIRATION_TIME}
  config:
    import: optional:file:.env
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
     host: ${REDIS_HOST}
     port: ${REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: ${SERVER_PORT}
logging:
  level:
    org:
      springframework:
        security: TRACE
        web: TRACE
frontend:
  url: ${FRONTEND_URL}